# Generated by Django 4.1.1 on 2022-09-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
