# Generated by Django 4.1.1 on 2022-09-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_foo_kitchen_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='phone_number',
            field=models.IntegerField(blank=True, default=444),
            preserve_default=False,
        ),
    ]
