# Generated by Django 4.1.3 on 2022-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0002_alter_starwarscard_ability_alter_starwarscard_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscard',
            name='DarkSideIcons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='lightSideIcons',
            field=models.IntegerField(null=True),
        ),
    ]
