# Generated by Django 4.1.3 on 2022-11-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0006_alter_starwarscard_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starwarscard',
            old_name='DarkSideIcons',
            new_name='darkSideIcons',
        ),
    ]
