# Generated by Django 4.1.2 on 2022-12-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0011_alter_starwarscard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscard',
            name='image',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
