# Generated by Django 4.1.2 on 2023-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0013_starwarscard_erratasymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarscard',
            name='errataDate',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starwarscard',
            name='errataNotes',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starwarscard',
            name='previousId',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
