# Generated by Django 4.1.2 on 2023-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0014_starwarscard_erratadate_starwarscard_erratanotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscard',
            name='errataNotes',
            field=models.TextField(default='', max_length=10000, null=True),
        ),
    ]
