# Generated by Django 4.1.2 on 2023-06-26 04:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0015_alter_starwarscard_erratanotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscard',
            name='ability',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='armor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='characteristics',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='conceptBy',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='darkSideIcons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='deploy',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='destiny',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='destinyValues',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='errataDate',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='errataNotes',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='errataSymbol',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='errataVersion',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='extraText',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='ferocity',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='forfeit',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='gametext',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='gempId',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='hyperspeed',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='icons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='imageUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='landspeed',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='legacy',
            field=models.BooleanField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='lightSideIcons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='lore',
            field=models.TextField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='maneuver',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='parsec',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='politics',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='power',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='previousId',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='rarity',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='set',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='side',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='sourceType',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='subType',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='uniqueness',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
