# Generated by Django 4.1.2 on 2023-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0017_starwarscard_backsideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarscard',
            name='backSideText',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='starwarscard',
            name='backSideTitle',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starwarscard',
            name='backsideImageUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='starwarscard',
            name='gametext',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
    ]
