# Generated by Django 4.1.3 on 2022-11-22 15:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='copies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='starwarscard',
            fields=[
                ('title', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('side', models.CharField(default='', max_length=200)),
                ('gametext', models.TextField(default='', max_length=200)),
                ('deploy', models.CharField(default='', max_length=200)),
                ('characteristics', models.CharField(default='', max_length=200)),
                ('destiny', models.CharField(default='', max_length=200)),
                ('forfeit', models.CharField(default='', max_length=200)),
                ('icons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('imageUrl', models.URLField(default='')),
                ('lore', models.TextField(default='', max_length=200)),
                ('power', models.CharField(default='', max_length=200)),
                ('subType', models.CharField(default='', max_length=200)),
                ('gempId', models.CharField(default='', max_length=30)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('set', models.CharField(default='', max_length=200)),
                ('rarity', models.CharField(default='', max_length=200)),
                ('conceptBy', models.TextField(default='', max_length=200)),
                ('legacy', models.BooleanField(default=False)),
                ('extraText', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('uniqueness', models.CharField(default='', max_length=2)),
                ('armor', models.CharField(default='', max_length=200)),
                ('errataVersion', models.CharField(default='', max_length=200)),
                ('sourceType', models.CharField(default='', max_length=200)),
                ('landspeed', models.CharField(default='', max_length=200)),
                ('ability', models.CharField(default='', max_length=200)),
                ('hyperspeed', models.CharField(default='', max_length=200)),
                ('maneuver', models.CharField(default='', max_length=200)),
                ('politics', models.CharField(default='', max_length=200)),
                ('parsec', models.CharField(default='', max_length=200)),
                ('lightSideIcons', models.IntegerField(blank=True)),
                ('DarkSideIcons', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='decklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('side', models.CharField(max_length=200)),
                ('card', models.ManyToManyField(through='swccg.copies', to='swccg.starwarscard')),
            ],
        ),
        migrations.AddField(
            model_name='copies',
            name='deck_list',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deck_list', to='swccg.decklist'),
        ),
        migrations.AddField(
            model_name='copies',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardname', to='swccg.starwarscard'),
        ),
    ]
