# Generated by Django 4.1.3 on 2022-11-22 15:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0004_alter_starwarscard_ability_alter_starwarscard_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscard',
            name='extraText',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, null=True), default=list, null=True, size=None),
        ),
    ]
