# Generated by Django 4.1.3 on 2022-11-22 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0005_alter_starwarscard_extratext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscard',
            name='icons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200), default=list, null=True, size=None),
        ),
    ]
