# Generated by Django 4.1.3 on 2022-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0007_rename_darksideicons_starwarscard_darksideicons'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarscard',
            name='ferocity',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
