# Generated by Django 4.1.2 on 2023-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0012_alter_starwarscard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarscard',
            name='errataSymbol',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
