# Generated by Django 4.1.2 on 2023-06-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0016_alter_starwarscard_ability_alter_starwarscard_armor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarscard',
            name='backSideImage',
            field=models.ImageField(blank=True, max_length=255, upload_to=''),
        ),
    ]
