# Generated by Django 4.1.2 on 2025-01-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swccg', '0018_starwarscard_backsidetext_starwarscard_backsidetitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='starwarscard',
            name='printableSlipType',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='starwarscard',
            name='printableSlipUrl',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
