# Generated by Django 5.1.9 on 2026-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swccg", "0019_starwarscard_printablesliptype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="starwarscard",
            name="legacy",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
