databases:
  - name: Star Wars CCG Card Database
    databaseName: Star Wars CCG Card Database
    user: Star Wars CCG Card Database

services:
  - type: web
    name: Star Wars CCG Card Database
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Star Wars CCG Card Database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
